# SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=ghcr.io/stacklok/waggle/base:latest
FROM ${BASE_IMAGE}

RUN apk add --no-cache nodejs npm
